name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:ci

    - name: Run Selenium tests
      run: |
        # Install Chrome
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        npm run test:selenium

    - name: Build project
      run: npm run build

    - name: Create extension package
      run: npm run package

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: klartext-extension
        path: klartext.zip
        retention-days: 5

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: klartext.zip
        tag_name: v${{ github.run_number }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
